### ISSUE TITLE
Problem with logicle transform in the GUI

### ISSUE THREAD

**Issue by har-wradim** [bpteague/cytoflow#60]
When changing the scale of an axis in any plot to logicle in cytoflow-0.4.1 under Ubuntu 16.04 x86_64 I get the following error in the GUI:

	Error: AttributeError: 'float' object has no attribute 'item'

	Location:   File "/home/har-wradim/.local/lib/python2.7/site-packages/cytoflow-0.4.1-py2.7-linux-x86_64.egg/cytoflow/utility/logicle_scale.py", line 186, in _get_W
	    r_value = neg_values.quantile(self.r).item()
	Thread: MainThread

I haven't dug any deeper, but the `quantile()` method seems to directly return a float, so just removing the `.item()` call helps in this case. I experience some other issues, but I believe they are not related to this problem.

Packages:

	python 2.7.12
	fcsparser 0.1.2
	matplotlib 2.0.0
	traits 4.6.0
	scipy 0.18.1
	numexpr 2.6.2
	bottleneck 1.2.0
	envisage 4.6.0
	pyface 4.4.0
	seaborn 0.7.1
	scikit-learn 0.18.1
	traitsui 5.1.0
	cytoflow 0.4.1
	numpy 1.12.0
	pandas 0.19.2

Here is the full log block around the exception:

	2017-02-17 15:45:07,932 DEBUG:root:FigureCanvasQtAggLocal.paintEvent: 
	2017-02-17 15:45:09,656 DEBUG:root:LocalWorkflow._view_changed :: (<cytoflowgui.view_plugins.scatterplot.ScatterplotPluginView object at 0x7f851a7a1f50>, 'changed', 'api')
	2017-02-17 15:45:09,659 DEBUG:root:RemoteWorkflow.recv_main :: UPDATE_VIEW
	2017-02-17 15:45:09,761 DEBUG:root:RemoteWorkflow._view_changed :: (<cytoflowgui.view_plugins.scatterplot.ScatterplotPluginView object at 0x7f857f2cd410>, 'changed', 'api')
	2017-02-17 15:45:09,761 DEBUG:root:RemoteWorkflowItem._current_view_trait_changed :: (<cytoflowgui.workflow_item.RemoteWorkflowItem object at 0x7f852b9a86b0>, 'api')
	2017-02-17 15:45:09,763 DEBUG:root:RemoteWorkflow._view_changed :: (<cytoflowgui.view_plugins.scatterplot.ScatterplotPluginView object at 0x7f857f2cd410>, 'changed', 'api')
	2017-02-17 15:45:09,763 DEBUG:root:RemoteWorkflowItem._current_view_trait_changed :: (<cytoflowgui.workflow_item.RemoteWorkflowItem object at 0x7f852b9a86b0>, 'api')
	2017-02-17 15:45:09,865 DEBUG:root:RemoteWorkflow._workflow_command :: (<cytoflowgui.workflow_item.RemoteWorkflowItem object at 0x7f852b9a86b0>, 'command', 'plot')
	2017-02-17 15:45:09,865 DEBUG:root:WorkflowItem.plot :: <cytoflowgui.workflow_item.RemoteWorkflowItem object at 0x7f852b9a86b0>
	2017-02-17 15:45:09,866 DEBUG:root:RemoteWorkflow._workflow_command :: (<cytoflowgui.workflow_item.RemoteWorkflowItem object at 0x7f852b9a86b0>, 'command', 'plot')
	2017-02-17 15:45:09,868 DEBUG:root:mpl_multiprocess_backend.new_figure_manager()
	2017-02-17 15:45:10,039 DEBUG:root:Exception in MainThread: Traceback (most recent call last):
	  File "/home/har-wradim/.local/lib/python2.7/site-packages/cytoflow-0.4.1-py2.7-linux-x86_64.egg/cytoflowgui/workflow.py", line 403, in run
	    fn()
	  File "/home/har-wradim/.local/lib/python2.7/site-packages/cytoflow-0.4.1-py2.7-linux-x86_64.egg/cytoflowgui/workflow_item.py", line 344, in plot
	    self.current_view.plot_wi(self)
	  File "/home/har-wradim/.local/lib/python2.7/site-packages/cytoflow-0.4.1-py2.7-linux-x86_64.egg/cytoflowgui/view_plugins/i_view_plugin.py", line 87, in plot_wi
	    self.plot(wi.result)
	  File "/home/har-wradim/.local/lib/python2.7/site-packages/cytoflow-0.4.1-py2.7-linux-x86_64.egg/cytoflow/views/scatterplot.py", line 155, in plot
	    ax.set_xscale(self.xscale, **xscale.mpl_params)
	  File "/home/har-wradim/.local/lib/python2.7/site-packages/traits/has_traits.py", line 895, in decorator
	    self.__dict__[ name ] = result = function( self )
	  File "/home/har-wradim/.local/lib/python2.7/site-packages/cytoflow-0.4.1-py2.7-linux-x86_64.egg/cytoflow/utility/logicle_scale.py", line 223, in _get_mpl_params
	    return {"logicle" : self.logicle,
	  File "/home/har-wradim/.local/lib/python2.7/site-packages/traits/has_traits.py", line 895, in decorator
	    self.__dict__[ name ] = result = function( self )
	  File "/home/har-wradim/.local/lib/python2.7/site-packages/cytoflow-0.4.1-py2.7-linux-x86_64.egg/cytoflow/utility/logicle_scale.py", line 199, in _get_logicle
	    if self.range is Undefined or self.W is Undefined:
	  File "/home/har-wradim/.local/lib/python2.7/site-packages/traits/has_traits.py", line 895, in decorator
	    self.__dict__[ name ] = result = function( self )
	  File "/home/har-wradim/.local/lib/python2.7/site-packages/cytoflow-0.4.1-py2.7-linux-x86_64.egg/cytoflow/utility/logicle_scale.py", line 186, in _get_W
	    r_value = neg_values.quantile(self.r).item()
	AttributeError: 'float' object has no attribute 'item'

	2017-02-17 15:45:10,039 ERROR:root:Error: AttributeError: 'float' object has no attribute 'item'

	Location:   File "/home/har-wradim/.local/lib/python2.7/site-packages/cytoflow-0.4.1-py2.7-linux-x86_64.egg/cytoflow/utility/logicle_scale.py", line 186, in _get_W
	    r_value = neg_values.quantile(self.r).item()
	Thread: MainThread
	2017-02-17 15:45:10,039 DEBUG:root:WorkflowItem.plot :: <cytoflowgui.workflow_item.RemoteWorkflowItem object at 0x7f852b9a86b0>
	2017-02-17 15:45:10,040 DEBUG:root:mpl_multiprocess_backend.new_figure_manager()
	2017-02-17 15:45:10,159 DEBUG:root:FigureCanvasQtAggLocal.paintEvent: 
	2017-02-17 15:45:10,286 DEBUG:root:Exception in MainThread: Traceback (most recent call last):
	  File "/home/har-wradim/.local/lib/python2.7/site-packages/cytoflow-0.4.1-py2.7-linux-x86_64.egg/cytoflowgui/workflow.py", line 403, in run
	    fn()
	  File "/home/har-wradim/.local/lib/python2.7/site-packages/cytoflow-0.4.1-py2.7-linux-x86_64.egg/cytoflowgui/workflow_item.py", line 344, in plot
	    self.current_view.plot_wi(self)
	  File "/home/har-wradim/.local/lib/python2.7/site-packages/cytoflow-0.4.1-py2.7-linux-x86_64.egg/cytoflowgui/view_plugins/i_view_plugin.py", line 87, in plot_wi
	    self.plot(wi.result)
	  File "/home/har-wradim/.local/lib/python2.7/site-packages/cytoflow-0.4.1-py2.7-linux-x86_64.egg/cytoflow/views/scatterplot.py", line 155, in plot
	    ax.set_xscale(self.xscale, **xscale.mpl_params)
	  File "/home/har-wradim/.local/lib/python2.7/site-packages/traits/has_traits.py", line 895, in decorator
	    self.__dict__[ name ] = result = function( self )
	  File "/home/har-wradim/.local/lib/python2.7/site-packages/cytoflow-0.4.1-py2.7-linux-x86_64.egg/cytoflow/utility/logicle_scale.py", line 223, in _get_mpl_params
	    return {"logicle" : self.logicle,
	  File "/home/har-wradim/.local/lib/python2.7/site-packages/traits/has_traits.py", line 895, in decorator
	    self.__dict__[ name ] = result = function( self )
	  File "/home/har-wradim/.local/lib/python2.7/site-packages/cytoflow-0.4.1-py2.7-linux-x86_64.egg/cytoflow/utility/logicle_scale.py", line 199, in _get_logicle
	    if self.range is Undefined or self.W is Undefined:
	  File "/home/har-wradim/.local/lib/python2.7/site-packages/traits/has_traits.py", line 895, in decorator
	    self.__dict__[ name ] = result = function( self )
	  File "/home/har-wradim/.local/lib/python2.7/site-packages/cytoflow-0.4.1-py2.7-linux-x86_64.egg/cytoflow/utility/logicle_scale.py", line 186, in _get_W
	    r_value = neg_values.quantile(self.r).item()
	AttributeError: 'float' object has no attribute 'item'

	2017-02-17 15:45:10,286 ERROR:root:Error: AttributeError: 'float' object has no attribute 'item'

	Location:   File "/home/har-wradim/.local/lib/python2.7/site-packages/cytoflow-0.4.1-py2.7-linux-x86_64.egg/cytoflow/utility/logicle_scale.py", line 186, in _get_W
	    r_value = neg_values.quantile(self.r).item()
	Thread: MainThread

**Comment by har-wradim** [comment]
Seems to be fixed by some commit(s) after the 0.4.1 release.
