### ISSUE TITLE
NonGuiException

### ISSUE THREAD

**Issue by har-wradim** [bpteague/cytoflow#62]
On every GUI launch I get the following exception:

	An exception has occurred.  Please report a problem from the Help menu!

	Afterwards, may need to restart Cytoflow to continue working.

	Error: NonGuiException

	Location:   File "/home/har-wradim/.local/lib/python2.7/site-packages/matplotlib/backend_bases.py", line 2620, in show
		raise NonGuiException()
	Thread: MainThread

Ubuntu 16.04 x86_64

PACKAGE VERSIONS: ['fcsparser 0.1.2', 'python 2.7.12 (default, Nov 19 2016, 06:48:10) \n[GCC 5.4.0 20160609]', 'matplotlib 1.5.3', 'traits 4.6.0', 'scipy 0.18.1', 'numexpr 2.4.6', 'bottleneck 1.0.0', 'envisage 4.6.0', 'pyface 5.1.0', 'seaborn 0.7.1', 'scikit-learn 0.18.1', 'traitsui 5.1.0', 'cytoflow 0.4.1', 'numpy 1.12.0', 'pandas 0.19.2']

Full log:

	fatal: Not a git repository (or any of the parent directories): .git
	/home/har-wradim/.local/lib/python2.7/site-packages/matplotlib/__init__.py:1357: UserWarning:  This call to matplotlib.use() has no effect
	because the backend has already been chosen;
	matplotlib.use() must be called *before* pylab, matplotlib.pyplot,
	or matplotlib.backends is imported for the first time.

	2017-02-28 10:29:20,298 DEBUG:envisage.application:---------- application starting ----------
	2017-02-28 10:29:20,298 DEBUG:envisage.plugin_manager:plugin envisage.core starting
	2017-02-28 10:29:20,323 DEBUG:envisage.provider_extension_registry:extensions to <envisage.preferences> <[[], [], ['file:///home/har-wradim/.local/lib/python2.7/site-packages/cytoflow-0.4.1-py2.7-linux-x86_64.egg/cytoflowgui/preferences.ini'], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], []]>
	2017-02-28 10:29:20,325 DEBUG:apptools.preferences.preferences:loading preferences from </home/har-wradim/.enthought/edu.mit.synbio.cytoflow/preferences.ini>
	2017-02-28 10:29:20,333 DEBUG:apptools.preferences.preferences:loading preferences from <<open file '/home/har-wradim/.local/lib/python2.7/site-packages/cytoflow-0.4.1-py2.7-linux-x86_64.egg/cytoflowgui/preferences.ini', mode 'rb' at 0x7f66b2985270>>
	2017-02-28 10:29:20,351 DEBUG:envisage.provider_extension_registry:extensions to <envisage.class_load_hooks> <[[], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], []]>
	2017-02-28 10:29:20,368 DEBUG:envisage.provider_extension_registry:extensions to <envisage.categories> <[[], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], []]>
	2017-02-28 10:29:20,385 DEBUG:envisage.provider_extension_registry:extensions to <envisage.service_offers> <[[], [<envisage.service_offer.ServiceOffer object at 0x7f66b29effb0>], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], []]>
	2017-02-28 10:29:20,385 DEBUG:envisage.service_registry:service <1> registered envisage.ui.tasks.preferences_dialog.PreferencesDialog
	2017-02-28 10:29:20,385 DEBUG:envisage.plugin_manager:plugin envisage.core started
	2017-02-28 10:29:20,386 DEBUG:envisage.plugin_manager:plugin envisage.ui.tasks starting
	2017-02-28 10:29:20,386 DEBUG:envisage.plugin_manager:plugin envisage.ui.tasks started
	2017-02-28 10:29:20,386 DEBUG:envisage.plugin_manager:plugin edu.mit.synbio.cytoflow starting
	2017-02-28 10:29:20,386 DEBUG:envisage.plugin_manager:plugin edu.mit.synbio.cytoflow started
	2017-02-28 10:29:20,386 DEBUG:envisage.plugin_manager:plugin edu.mit.synbio.cytoflowgui.view.table starting
	2017-02-28 10:29:20,386 DEBUG:envisage.plugin_manager:plugin edu.mit.synbio.cytoflowgui.view.table started
	2017-02-28 10:29:20,386 DEBUG:envisage.plugin_manager:plugin edu.mit.synbio.cytoflowgui.view.stats2d starting
	2017-02-28 10:29:20,387 DEBUG:envisage.plugin_manager:plugin edu.mit.synbio.cytoflowgui.view.stats2d started
	2017-02-28 10:29:20,387 DEBUG:envisage.plugin_manager:plugin edu.mit.synbio.cytoflowgui.view.stats1d starting
	2017-02-28 10:29:20,387 DEBUG:envisage.plugin_manager:plugin edu.mit.synbio.cytoflowgui.view.stats1d started
	2017-02-28 10:29:20,387 DEBUG:envisage.plugin_manager:plugin edu.mit.synbio.cytoflowgui.view.barchart starting
	2017-02-28 10:29:20,387 DEBUG:envisage.plugin_manager:plugin edu.mit.synbio.cytoflowgui.view.barchart started
	2017-02-28 10:29:20,387 DEBUG:envisage.plugin_manager:plugin edu.mit.synbio.cytoflowgui.view.violin starting
	2017-02-28 10:29:20,387 DEBUG:envisage.plugin_manager:plugin edu.mit.synbio.cytoflowgui.view.violin started
	2017-02-28 10:29:20,387 DEBUG:envisage.plugin_manager:plugin edu.mit.synbio.cytoflowgui.view.kde2d starting
	2017-02-28 10:29:20,387 DEBUG:envisage.plugin_manager:plugin edu.mit.synbio.cytoflowgui.view.kde2d started
	2017-02-28 10:29:20,387 DEBUG:envisage.plugin_manager:plugin edu.mit.synbio.cytoflowgui.view.kde1d starting
	2017-02-28 10:29:20,388 DEBUG:envisage.plugin_manager:plugin edu.mit.synbio.cytoflowgui.view.kde1d started
	2017-02-28 10:29:20,388 DEBUG:envisage.plugin_manager:plugin edu.mit.synbio.cytoflowgui.view.histogram2d starting
	2017-02-28 10:29:20,388 DEBUG:envisage.plugin_manager:plugin edu.mit.synbio.cytoflowgui.view.histogram2d started
	2017-02-28 10:29:20,388 DEBUG:envisage.plugin_manager:plugin edu.mit.synbio.cytoflowgui.view.scatterplot starting
	2017-02-28 10:29:20,388 DEBUG:envisage.plugin_manager:plugin edu.mit.synbio.cytoflowgui.view.scatterplot started
	2017-02-28 10:29:20,388 DEBUG:envisage.plugin_manager:plugin edu.mit.synbio.cytoflowgui.view.histogram starting
	2017-02-28 10:29:20,388 DEBUG:envisage.plugin_manager:plugin edu.mit.synbio.cytoflowgui.view.histogram started
	2017-02-28 10:29:20,388 DEBUG:envisage.plugin_manager:plugin edu.mit.synbio.cytoflowgui.op_plugins.ratio starting
	2017-02-28 10:29:20,388 DEBUG:envisage.plugin_manager:plugin edu.mit.synbio.cytoflowgui.op_plugins.ratio started
	2017-02-28 10:29:20,388 DEBUG:envisage.plugin_manager:plugin edu.mit.synbio.cytoflowgui.op_plugins.transform_statistic starting
	2017-02-28 10:29:20,389 DEBUG:envisage.plugin_manager:plugin edu.mit.synbio.cytoflowgui.op_plugins.transform_statistic started
	2017-02-28 10:29:20,389 DEBUG:envisage.plugin_manager:plugin edu.mit.synbio.cytoflowgui.op_plugins.channel_statistic starting
	2017-02-28 10:29:20,389 DEBUG:envisage.plugin_manager:plugin edu.mit.synbio.cytoflowgui.op_plugins.channel_statistic started
	2017-02-28 10:29:20,389 DEBUG:envisage.plugin_manager:plugin edu.mit.synbio.cytoflowgui.op_plugins.tasbe starting
	2017-02-28 10:29:20,389 DEBUG:envisage.plugin_manager:plugin edu.mit.synbio.cytoflowgui.op_plugins.tasbe started
	2017-02-28 10:29:20,389 DEBUG:envisage.plugin_manager:plugin edu.mit.synbio.cytoflowgui.op_plugins.color_translation starting
	2017-02-28 10:29:20,389 DEBUG:envisage.plugin_manager:plugin edu.mit.synbio.cytoflowgui.op_plugins.color_translation started
	2017-02-28 10:29:20,389 DEBUG:envisage.plugin_manager:plugin edu.mit.synbio.cytoflowgui.op_plugins.autofluorescence starting
	2017-02-28 10:29:20,389 DEBUG:envisage.plugin_manager:plugin edu.mit.synbio.cytoflowgui.op_plugins.autofluorescence started
	2017-02-28 10:29:20,390 DEBUG:envisage.plugin_manager:plugin edu.mit.synbio.cytoflowgui.op_plugins.bead_calibrate starting
	2017-02-28 10:29:20,390 DEBUG:envisage.plugin_manager:plugin edu.mit.synbio.cytoflowgui.op_plugins.bead_calibrate started
	2017-02-28 10:29:20,390 DEBUG:envisage.plugin_manager:plugin edu.mit.synbio.cytoflowgui.op_plugins.bleedthrough_piecewise starting
	2017-02-28 10:29:20,390 DEBUG:envisage.plugin_manager:plugin edu.mit.synbio.cytoflowgui.op_plugins.bleedthrough_piecewise started
	2017-02-28 10:29:20,390 DEBUG:envisage.plugin_manager:plugin edu.mit.synbio.cytoflowgui.op_plugins.bleedthrough_linear starting
	2017-02-28 10:29:20,390 DEBUG:envisage.plugin_manager:plugin edu.mit.synbio.cytoflowgui.op_plugins.bleedthrough_linear started
	2017-02-28 10:29:20,390 DEBUG:envisage.plugin_manager:plugin edu.mit.synbio.cytoflowgui.op_plugins.gaussian_2d starting
	2017-02-28 10:29:20,390 DEBUG:envisage.plugin_manager:plugin edu.mit.synbio.cytoflowgui.op_plugins.gaussian_2d started
	2017-02-28 10:29:20,390 DEBUG:envisage.plugin_manager:plugin edu.mit.synbio.cytoflowgui.op_plugins.gaussian_1d starting
	2017-02-28 10:29:20,391 DEBUG:envisage.plugin_manager:plugin edu.mit.synbio.cytoflowgui.op_plugins.gaussian_1d started
	2017-02-28 10:29:20,391 DEBUG:envisage.plugin_manager:plugin edu.mit.synbio.cytoflowgui.op_plugins.binning starting
	2017-02-28 10:29:20,391 DEBUG:envisage.plugin_manager:plugin edu.mit.synbio.cytoflowgui.op_plugins.binning started
	2017-02-28 10:29:20,391 DEBUG:envisage.plugin_manager:plugin edu.mit.synbio.cytoflowgui.op_plugins.polygon starting
	2017-02-28 10:29:20,391 DEBUG:envisage.plugin_manager:plugin edu.mit.synbio.cytoflowgui.op_plugins.polygon started
	2017-02-28 10:29:20,391 DEBUG:envisage.plugin_manager:plugin edu.mit.synbio.cytoflowgui.op_plugins.quad starting
	2017-02-28 10:29:20,391 DEBUG:envisage.plugin_manager:plugin edu.mit.synbio.cytoflowgui.op_plugins.quad started
	2017-02-28 10:29:20,391 DEBUG:envisage.plugin_manager:plugin edu.mit.synbio.cytoflowgui.op_plugins.range2d starting
	2017-02-28 10:29:20,392 DEBUG:envisage.plugin_manager:plugin edu.mit.synbio.cytoflowgui.op_plugins.range2d started
	2017-02-28 10:29:20,392 DEBUG:envisage.plugin_manager:plugin edu.mit.synbio.cytoflowgui.op_plugins.range starting
	2017-02-28 10:29:20,392 DEBUG:envisage.plugin_manager:plugin edu.mit.synbio.cytoflowgui.op_plugins.range started
	2017-02-28 10:29:20,392 DEBUG:envisage.plugin_manager:plugin edu.mit.synbio.cytoflowgui.op_plugins.threshold starting
	2017-02-28 10:29:20,392 DEBUG:envisage.plugin_manager:plugin edu.mit.synbio.cytoflowgui.op_plugins.threshold started
	2017-02-28 10:29:20,392 DEBUG:envisage.plugin_manager:plugin edu.mit.synbio.cytoflowgui.op_plugins.import starting
	2017-02-28 10:29:20,392 DEBUG:envisage.plugin_manager:plugin edu.mit.synbio.cytoflowgui.op_plugins.import started
	2017-02-28 10:29:20,392 DEBUG:envisage.application:---------- application started ----------
	2017-02-28 10:29:20,392 DEBUG:envisage.ui.tasks.tasks_application:Tasks state location is /home/har-wradim/.enthought/edu.mit.synbio.cytoflow/tasks/qt4
	2017-02-28 10:29:20,411 DEBUG:envisage.provider_extension_registry:extensions to <envisage.ui.tasks.tasks> <[[], [], [<envisage.ui.tasks.task_factory.TaskFactory object at 0x7f66b299c770>], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], []]>
	2017-02-28 10:29:20,431 DEBUG:envisage.provider_extension_registry:extensions to <envisage.ui.tasks.task_extensions> <[[], [<envisage.ui.tasks.task_extension.TaskExtension object at 0x7f66b29b9290>], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], []]>
	2017-02-28 10:29:20,444 DEBUG:envisage.provider_extension_registry:extensions to <edu.mit.synbio.cytoflow.op_plugins> <[[], [], [], [], [], [], [], [], [], [], [], [], [], [<cytoflowgui.op_plugins.ratio.RatioPlugin object at 0x7f66b3215f50>], [<cytoflowgui.op_plugins.xform_stat.TransformStatisticPlugin object at 0x7f66b3215fb0>], [<cytoflowgui.op_plugins.channel_stat.ChannelStatisticPlugin object at 0x7f66b3237050>], [<cytoflowgui.op_plugins.tasbe.TasbePlugin object at 0x7f66b32370b0>], [<cytoflowgui.op_plugins.color_translation.ColorTranslationPlugin object at 0x7f66b3237110>], [<cytoflowgui.op_plugins.autofluorescence.AutofluorescencePlugin object at 0x7f66b3237170>], [<cytoflowgui.op_plugins.bead_calibration.BeadCalibrationPlugin object at 0x7f66b32371d0>], [<cytoflowgui.op_plugins.bleedthrough_piecewise.BleedthroughPiecewisePlugin object at 0x7f66b3237230>], [<cytoflowgui.op_plugins.bleedthrough_linear.BleedthroughLinearPlugin object at 0x7f66b3237290>], [<cytoflowgui.op_plugins.gaussian_2d.GaussianMixture2DPlugin object at 0x7f66b32372f0>], [<cytoflowgui.op_plugins.gaussian_1d.GaussianMixture1DPlugin object at 0x7f66b3237350>], [<cytoflowgui.op_plugins.binning.BinningPlugin object at 0x7f66b32373b0>], [<cytoflowgui.op_plugins.polygon.PolygonPlugin object at 0x7f66b3237410>], [<cytoflowgui.op_plugins.quad.QuadPlugin object at 0x7f66b3237470>], [<cytoflowgui.op_plugins.range2d.Range2DPlugin object at 0x7f66b32374d0>], [<cytoflowgui.op_plugins.range.RangePlugin object at 0x7f66b3237530>], [<cytoflowgui.op_plugins.threshold.ThresholdPlugin object at 0x7f66b3237590>], [<cytoflowgui.op_plugins.import_op.ImportPlugin object at 0x7f66b32375f0>]]>
	2017-02-28 10:29:20,459 DEBUG:envisage.provider_extension_registry:extensions to <edu.mit.synbio.cytoflow.view_plugins> <[[], [], [], [<cytoflowgui.view_plugins.table.TablePlugin object at 0x7f66b3215b90>], [<cytoflowgui.view_plugins.stats_2d.Stats2DPlugin object at 0x7f66b3215bf0>], [<cytoflowgui.view_plugins.stats_1d.Stats1DPlugin object at 0x7f66b3215c50>], [<cytoflowgui.view_plugins.bar_chart.BarChartPlugin object at 0x7f66b3215cb0>], [<cytoflowgui.view_plugins.violin.ViolinPlotPlugin object at 0x7f66b3215d10>], [<cytoflowgui.view_plugins.kde_2d.Kde2DPlugin object at 0x7f66b3215d70>], [<cytoflowgui.view_plugins.kde_1d.Kde1DPlugin object at 0x7f66b3215dd0>], [<cytoflowgui.view_plugins.histogram_2d.Histogram2DPlugin object at 0x7f66b3215e30>], [<cytoflowgui.view_plugins.scatterplot.ScatterplotPlugin object at 0x7f66b3215e90>], [<cytoflowgui.view_plugins.histogram.HistogramPlugin object at 0x7f66b3215ef0>], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], []]>
	2017-02-28 10:29:20,630 DEBUG:root:LocalWorkflow._on_workflow_add_remove_items :: (0, [], [<WorkflowItem: ImportPluginOp>])
	2017-02-28 10:29:20,649 DEBUG:root:RemoteWorkflow.recv_main :: ADD_ITEMS
	2017-02-28 10:29:20,655 DEBUG:root:RemoteWorkflow._on_workflow_add_remove_items :: (0, [], [<RemoteWorkflowItem: ImportPluginOp>])
	2017-02-28 10:29:20,860 DEBUG:root:LocalWorkflow._on_selected_changed :: (<cytoflowgui.workflow.Workflow object at 0x7f66b29b92f0>, 'selected', None, <WorkflowItem: ImportPluginOp>)
	2017-02-28 10:29:20,860 DEBUG:root:RemoteWorkflow.recv_main :: SELECT
	2017-02-28 10:29:20,957 DEBUG:root:FigureCanvasQTAggLocal.resizeEvent : (663, 638)
	2017-02-28 10:29:20,958 DEBUG:root:FigureCanvasQTAggLocal.send_to_remote: (u'RESIZE', 8.2875, 7.975)
	2017-02-28 10:29:20,969 DEBUG:root:FigureCanvasQTAggLocal.resizeEvent : (663, 655)
	2017-02-28 10:29:20,970 DEBUG:pyface.ui.qt4.gui:---------- starting GUI event loop ----------
	2017-02-28 10:29:21,058 DEBUG:root:FigureCanvasQTAggLocal.send_to_remote: (u'RESIZE', 8.2875, 8.1875)
	2017-02-28 10:29:21,061 DEBUG:root:RemoteWorkflow._workflow_command :: (<RemoteWorkflowItem: ImportPluginOp>, 'command', 'plot')
	2017-02-28 10:29:21,061 DEBUG:root:WorkflowItem.plot :: <RemoteWorkflowItem: ImportPluginOp>
	2017-02-28 10:29:21,062 DEBUG:root:mpl_multiprocess_backend.new_figure_manager()
	2017-02-28 10:29:21,064 DEBUG:root:FigureCanvasAggRemote.listen_for_remote :: RESIZE
	2017-02-28 10:29:21,064 DEBUG:root:FigureCanvasAggRemote.draw()
	2017-02-28 10:29:21,075 DEBUG:root:FigureCanvasQTAggLocal.listen_for_remote :: DRAW
	2017-02-28 10:29:21,070 DEBUG:root:FigureCanvasAggRemote.send_to_remote
	2017-02-28 10:29:21,072 DEBUG:root:FigureCanvasAggRemote.listen_for_remote :: RESIZE
	2017-02-28 10:29:21,076 DEBUG:root:FigureCanvasQtAggLocal.paintEvent: 
	2017-02-28 10:29:21,073 DEBUG:root:FigureCanvasAggRemote.draw()
	2017-02-28 10:29:21,079 DEBUG:root:FigureCanvasAggRemote.send_to_remote
	2017-02-28 10:29:21,086 DEBUG:root:FigureCanvasQTAggLocal.listen_for_remote :: DRAW
	2017-02-28 10:29:21,084 DEBUG:root:Exception in MainThread: Traceback (most recent call last):
	  File "/home/har-wradim/.local/lib/python2.7/site-packages/cytoflow-0.4.1-py2.7-linux-x86_64.egg/cytoflowgui/workflow.py", line 414, in run
		fn()
	  File "/home/har-wradim/.local/lib/python2.7/site-packages/cytoflow-0.4.1-py2.7-linux-x86_64.egg/cytoflowgui/workflow_item.py", line 387, in plot
		plt.show()
	  File "/home/har-wradim/.local/lib/python2.7/site-packages/matplotlib/pyplot.py", line 252, in show
		return _show(*args, **kw)
	  File "/home/har-wradim/.local/lib/python2.7/site-packages/matplotlib/backend_bases.py", line 162, in __call__
		manager.show()
	  File "/home/har-wradim/.local/lib/python2.7/site-packages/matplotlib/backend_bases.py", line 2620, in show
		raise NonGuiException()
	NonGuiException

	2017-02-28 10:29:21,084 ERROR:root:Error: NonGuiException

	Location:   File "/home/har-wradim/.local/lib/python2.7/site-packages/matplotlib/backend_bases.py", line 2620, in show
		raise NonGuiException()
	Thread: MainThread
	2017-02-28 10:29:21,138 DEBUG:root:FigureCanvasQtAggLocal.paintEvent: 
	2017-02-28 10:29:21,189 DEBUG:root:FigureCanvasQtAggLocal.paintEvent: 
	2017-02-28 10:29:23,812 DEBUG:root:FigureCanvasQtAggLocal.paintEvent: 
	2017-02-28 10:29:25,483 DEBUG:envisage.application:---------- application stopping ----------
	2017-02-28 10:29:25,484 DEBUG:envisage.plugin_manager:plugin edu.mit.synbio.cytoflowgui.op_plugins.import stopping
	2017-02-28 10:29:25,484 DEBUG:envisage.plugin_manager:plugin edu.mit.synbio.cytoflowgui.op_plugins.import stopped
	2017-02-28 10:29:25,485 DEBUG:envisage.plugin_manager:plugin edu.mit.synbio.cytoflowgui.op_plugins.threshold stopping
	2017-02-28 10:29:25,486 DEBUG:envisage.plugin_manager:plugin edu.mit.synbio.cytoflowgui.op_plugins.threshold stopped
	2017-02-28 10:29:25,486 DEBUG:envisage.plugin_manager:plugin edu.mit.synbio.cytoflowgui.op_plugins.range stopping
	2017-02-28 10:29:25,487 DEBUG:envisage.plugin_manager:plugin edu.mit.synbio.cytoflowgui.op_plugins.range stopped
	2017-02-28 10:29:25,487 DEBUG:envisage.plugin_manager:plugin edu.mit.synbio.cytoflowgui.op_plugins.range2d stopping
	2017-02-28 10:29:25,488 DEBUG:envisage.plugin_manager:plugin edu.mit.synbio.cytoflowgui.op_plugins.range2d stopped
	2017-02-28 10:29:25,488 DEBUG:envisage.plugin_manager:plugin edu.mit.synbio.cytoflowgui.op_plugins.quad stopping
	2017-02-28 10:29:25,488 DEBUG:envisage.plugin_manager:plugin edu.mit.synbio.cytoflowgui.op_plugins.quad stopped
	2017-02-28 10:29:25,489 DEBUG:envisage.plugin_manager:plugin edu.mit.synbio.cytoflowgui.op_plugins.polygon stopping
	2017-02-28 10:29:25,489 DEBUG:envisage.plugin_manager:plugin edu.mit.synbio.cytoflowgui.op_plugins.polygon stopped
	2017-02-28 10:29:25,489 DEBUG:envisage.plugin_manager:plugin edu.mit.synbio.cytoflowgui.op_plugins.binning stopping
	2017-02-28 10:29:25,490 DEBUG:envisage.plugin_manager:plugin edu.mit.synbio.cytoflowgui.op_plugins.binning stopped
	2017-02-28 10:29:25,490 DEBUG:envisage.plugin_manager:plugin edu.mit.synbio.cytoflowgui.op_plugins.gaussian_1d stopping
	2017-02-28 10:29:25,490 DEBUG:envisage.plugin_manager:plugin edu.mit.synbio.cytoflowgui.op_plugins.gaussian_1d stopped
	2017-02-28 10:29:25,490 DEBUG:envisage.plugin_manager:plugin edu.mit.synbio.cytoflowgui.op_plugins.gaussian_2d stopping
	2017-02-28 10:29:25,491 DEBUG:envisage.plugin_manager:plugin edu.mit.synbio.cytoflowgui.op_plugins.gaussian_2d stopped
	2017-02-28 10:29:25,491 DEBUG:envisage.plugin_manager:plugin edu.mit.synbio.cytoflowgui.op_plugins.bleedthrough_linear stopping
	2017-02-28 10:29:25,491 DEBUG:envisage.plugin_manager:plugin edu.mit.synbio.cytoflowgui.op_plugins.bleedthrough_linear stopped
	2017-02-28 10:29:25,492 DEBUG:envisage.plugin_manager:plugin edu.mit.synbio.cytoflowgui.op_plugins.bleedthrough_piecewise stopping
	2017-02-28 10:29:25,492 DEBUG:envisage.plugin_manager:plugin edu.mit.synbio.cytoflowgui.op_plugins.bleedthrough_piecewise stopped
	2017-02-28 10:29:25,493 DEBUG:envisage.plugin_manager:plugin edu.mit.synbio.cytoflowgui.op_plugins.bead_calibrate stopping
	2017-02-28 10:29:25,493 DEBUG:envisage.plugin_manager:plugin edu.mit.synbio.cytoflowgui.op_plugins.bead_calibrate stopped
	2017-02-28 10:29:25,493 DEBUG:envisage.plugin_manager:plugin edu.mit.synbio.cytoflowgui.op_plugins.autofluorescence stopping
	2017-02-28 10:29:25,494 DEBUG:envisage.plugin_manager:plugin edu.mit.synbio.cytoflowgui.op_plugins.autofluorescence stopped
	2017-02-28 10:29:25,494 DEBUG:envisage.plugin_manager:plugin edu.mit.synbio.cytoflowgui.op_plugins.color_translation stopping
	2017-02-28 10:29:25,495 DEBUG:envisage.plugin_manager:plugin edu.mit.synbio.cytoflowgui.op_plugins.color_translation stopped
	2017-02-28 10:29:25,495 DEBUG:envisage.plugin_manager:plugin edu.mit.synbio.cytoflowgui.op_plugins.tasbe stopping
	2017-02-28 10:29:25,495 DEBUG:envisage.plugin_manager:plugin edu.mit.synbio.cytoflowgui.op_plugins.tasbe stopped
	2017-02-28 10:29:25,496 DEBUG:envisage.plugin_manager:plugin edu.mit.synbio.cytoflowgui.op_plugins.channel_statistic stopping
	2017-02-28 10:29:25,496 DEBUG:envisage.plugin_manager:plugin edu.mit.synbio.cytoflowgui.op_plugins.channel_statistic stopped
	2017-02-28 10:29:25,497 DEBUG:envisage.plugin_manager:plugin edu.mit.synbio.cytoflowgui.op_plugins.transform_statistic stopping
	2017-02-28 10:29:25,497 DEBUG:envisage.plugin_manager:plugin edu.mit.synbio.cytoflowgui.op_plugins.transform_statistic stopped
	2017-02-28 10:29:25,497 DEBUG:envisage.plugin_manager:plugin edu.mit.synbio.cytoflowgui.op_plugins.ratio stopping
	2017-02-28 10:29:25,498 DEBUG:envisage.plugin_manager:plugin edu.mit.synbio.cytoflowgui.op_plugins.ratio stopped
	2017-02-28 10:29:25,498 DEBUG:envisage.plugin_manager:plugin edu.mit.synbio.cytoflowgui.view.histogram stopping
	2017-02-28 10:29:25,498 DEBUG:envisage.plugin_manager:plugin edu.mit.synbio.cytoflowgui.view.histogram stopped
	2017-02-28 10:29:25,498 DEBUG:envisage.plugin_manager:plugin edu.mit.synbio.cytoflowgui.view.scatterplot stopping
	2017-02-28 10:29:25,499 DEBUG:envisage.plugin_manager:plugin edu.mit.synbio.cytoflowgui.view.scatterplot stopped
	2017-02-28 10:29:25,499 DEBUG:envisage.plugin_manager:plugin edu.mit.synbio.cytoflowgui.view.histogram2d stopping
	2017-02-28 10:29:25,499 DEBUG:envisage.plugin_manager:plugin edu.mit.synbio.cytoflowgui.view.histogram2d stopped
	2017-02-28 10:29:25,499 DEBUG:envisage.plugin_manager:plugin edu.mit.synbio.cytoflowgui.view.kde1d stopping
	2017-02-28 10:29:25,500 DEBUG:envisage.plugin_manager:plugin edu.mit.synbio.cytoflowgui.view.kde1d stopped
	2017-02-28 10:29:25,500 DEBUG:envisage.plugin_manager:plugin edu.mit.synbio.cytoflowgui.view.kde2d stopping
	2017-02-28 10:29:25,500 DEBUG:envisage.plugin_manager:plugin edu.mit.synbio.cytoflowgui.view.kde2d stopped
	2017-02-28 10:29:25,500 DEBUG:envisage.plugin_manager:plugin edu.mit.synbio.cytoflowgui.view.violin stopping
	2017-02-28 10:29:25,501 DEBUG:envisage.plugin_manager:plugin edu.mit.synbio.cytoflowgui.view.violin stopped
	2017-02-28 10:29:25,501 DEBUG:envisage.plugin_manager:plugin edu.mit.synbio.cytoflowgui.view.barchart stopping
	2017-02-28 10:29:25,501 DEBUG:envisage.plugin_manager:plugin edu.mit.synbio.cytoflowgui.view.barchart stopped
	2017-02-28 10:29:25,502 DEBUG:envisage.plugin_manager:plugin edu.mit.synbio.cytoflowgui.view.stats1d stopping
	2017-02-28 10:29:25,502 DEBUG:envisage.plugin_manager:plugin edu.mit.synbio.cytoflowgui.view.stats1d stopped
	2017-02-28 10:29:25,502 DEBUG:envisage.plugin_manager:plugin edu.mit.synbio.cytoflowgui.view.stats2d stopping
	2017-02-28 10:29:25,503 DEBUG:envisage.plugin_manager:plugin edu.mit.synbio.cytoflowgui.view.stats2d stopped
	2017-02-28 10:29:25,503 DEBUG:envisage.plugin_manager:plugin edu.mit.synbio.cytoflowgui.view.table stopping
	2017-02-28 10:29:25,503 DEBUG:envisage.plugin_manager:plugin edu.mit.synbio.cytoflowgui.view.table stopped
	2017-02-28 10:29:25,503 DEBUG:envisage.plugin_manager:plugin edu.mit.synbio.cytoflow stopping
	2017-02-28 10:29:25,504 DEBUG:envisage.plugin_manager:plugin edu.mit.synbio.cytoflow stopped
	2017-02-28 10:29:25,504 DEBUG:envisage.plugin_manager:plugin envisage.ui.tasks stopping
	2017-02-28 10:29:25,504 DEBUG:envisage.plugin_manager:plugin envisage.ui.tasks stopped
	2017-02-28 10:29:25,505 DEBUG:envisage.plugin_manager:plugin envisage.core stopping
	2017-02-28 10:29:25,505 DEBUG:envisage.service_registry:service <1> unregistered
	2017-02-28 10:29:25,506 DEBUG:envisage.plugin_manager:plugin envisage.core stopped
	2017-02-28 10:29:25,506 DEBUG:apptools.preferences.preferences:saving preferences to </home/har-wradim/.enthought/edu.mit.synbio.cytoflow/preferences.ini>
	2017-02-28 10:29:25,507 DEBUG:envisage.application:---------- application stopped ----------
	2017-02-28 10:29:25,520 ERROR:root:Remote process exited with None
	Exception in thread monitor remote process (most likely raised during interpreter shutdown):
	Traceback (most recent call last):
	  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
	  File "/usr/lib/python2.7/threading.py", line 754, in run
	  File "/home/har-wradim/.local/lib/python2.7/site-packages/cytoflow-0.4.1-py2.7-linux-x86_64.egg/cytoflowgui/run.py", line 260, in monitor_remote_process
	  File "/usr/lib/python2.7/logging/__init__.py", line 1603, in error
	  File "/usr/lib/python2.7/logging/__init__.py", line 1193, in error
	  File "/usr/lib/python2.7/logging/__init__.py", line 1286, in _log
	  File "/usr/lib/python2.7/logging/__init__.py", line 1296, in handle
	  File "/usr/lib/python2.7/logging/__init__.py", line 1336, in callHandlers
	  File "/usr/lib/python2.7/logging/__init__.py", line 761, in handle
	  File "/usr/lib/python2.7/logging/__init__.py", line 715, in release
	  File "/usr/lib/python2.7/threading.py", line 203, in release
	<type 'exceptions.TypeError'>: 'NoneType' object is not callable

**Comment by bpteague** [comment]
That's very interesting!  It looks like you're invoking the GUI by running `cytoflow` from the command line? That breaks for me too; I'll see if I can fix it.

In the meantime, you could try running the GUI by invoking the Python interpreter on the proper module: `python /home/har-wradim/.local/lib/python2.7/site-packages/cytoflow-0.4.1-py2.7-linux-x86_64.egg/cytoflowgui/run.py` or some-such.

You might also consider trying the PyInstaller-bundled executable.  You can get it at http://bpteague.github.io/cytoflow/  And if you want to try a bleeding-edge binary, the latest builds from Git are at https://bintray.com/bpteague/cytoflow/cytoflow#files

**Comment by bpteague** [comment]
PS -- *thank you* for all your bug reports!  I hope, despite the bugs, that you are finding Cytoflow more useful than frustrating.  The next version crashes much less frequently (-: and will hopefully be out in the next week or so!

**Comment by bpteague** [comment]
I think this is fixed by 8a183617b8eeabad1dfa8825dca166116753eccf. I'll check it on an Ubuntu 16.04 VM tomorrow; but if it's not fixed in 0.5, please re-open.
